
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CmiWS", targetNamespace = "http://controllers.cmi.api.ensas.com/", wsdlLocation = "http://localhost:8585/CmiWS?wsdl")
public class CmiWS
    extends Service
{

    private final static URL CMIWS_WSDL_LOCATION;
    private final static WebServiceException CMIWS_EXCEPTION;
    private final static QName CMIWS_QNAME = new QName("http://controllers.cmi.api.ensas.com/", "CmiWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8585/CmiWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMIWS_WSDL_LOCATION = url;
        CMIWS_EXCEPTION = e;
    }

    public CmiWS() {
        super(__getWsdlLocation(), CMIWS_QNAME);
    }

    public CmiWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMIWS_QNAME, features);
    }

    public CmiWS(URL wsdlLocation) {
        super(wsdlLocation, CMIWS_QNAME);
    }

    public CmiWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMIWS_QNAME, features);
    }

    public CmiWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmiWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CmiWebService
     */
    @WebEndpoint(name = "CmiWebServicePort")
    public CmiWebService getCmiWebServicePort() {
        return super.getPort(new QName("http://controllers.cmi.api.ensas.com/", "CmiWebServicePort"), CmiWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmiWebService
     */
    @WebEndpoint(name = "CmiWebServicePort")
    public CmiWebService getCmiWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controllers.cmi.api.ensas.com/", "CmiWebServicePort"), CmiWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMIWS_EXCEPTION!= null) {
            throw CMIWS_EXCEPTION;
        }
        return CMIWS_WSDL_LOCATION;
    }

}
