
package mypackage;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CmiWebService", targetNamespace = "http://controllers.cmi.api.ensas.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CmiWebService {


    /**
     * 
     * @param client
     * @return
     *     returns mypackage.Client
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveClient", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.SaveClient")
    @ResponseWrapper(localName = "saveClientResponse", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.SaveClientResponse")
    @Action(input = "http://controllers.cmi.api.ensas.com/CmiWebService/saveClientRequest", output = "http://controllers.cmi.api.ensas.com/CmiWebService/saveClientResponse")
    public Client saveClient(
        @WebParam(name = "client", targetNamespace = "")
        Client client);

    /**
     * 
     * @param client
     * @return
     *     returns mypackage.Client
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateClient", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.UpdateClient")
    @ResponseWrapper(localName = "updateClientResponse", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.UpdateClientResponse")
    @Action(input = "http://controllers.cmi.api.ensas.com/CmiWebService/updateClientRequest", output = "http://controllers.cmi.api.ensas.com/CmiWebService/updateClientResponse")
    public Client updateClient(
        @WebParam(name = "client", targetNamespace = "")
        Client client);

    /**
     * 
     * @return
     *     returns java.util.List<mypackage.Client>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListClient", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetListClient")
    @ResponseWrapper(localName = "getListClientResponse", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetListClientResponse")
    @Action(input = "http://controllers.cmi.api.ensas.com/CmiWebService/getListClientRequest", output = "http://controllers.cmi.api.ensas.com/CmiWebService/getListClientResponse")
    public List<Client> getListClient();

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "deleteClient", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.DeleteClient")
    @ResponseWrapper(localName = "deleteClientResponse", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.DeleteClientResponse")
    @Action(input = "http://controllers.cmi.api.ensas.com/CmiWebService/deleteClientRequest", output = "http://controllers.cmi.api.ensas.com/CmiWebService/deleteClientResponse")
    public void deleteClient(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param token
     * @return
     *     returns java.util.List<mypackage.Transaction>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListTransaction", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetListTransaction")
    @ResponseWrapper(localName = "getListTransactionResponse", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetListTransactionResponse")
    @Action(input = "http://controllers.cmi.api.ensas.com/CmiWebService/getListTransactionRequest", output = "http://controllers.cmi.api.ensas.com/CmiWebService/getListTransactionResponse")
    public List<Transaction> getListTransaction(
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param num
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIsActivated", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetIsActivated")
    @ResponseWrapper(localName = "getIsActivatedResponse", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetIsActivatedResponse")
    @Action(input = "http://controllers.cmi.api.ensas.com/CmiWebService/getIsActivatedRequest", output = "http://controllers.cmi.api.ensas.com/CmiWebService/getIsActivatedResponse")
    public boolean getIsActivated(
        @WebParam(name = "num", targetNamespace = "")
        String num);

    /**
     * 
     * @return
     *     returns java.util.List<mypackage.Creancier>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListCreancier", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetListCreancier")
    @ResponseWrapper(localName = "getListCreancierResponse", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetListCreancierResponse")
    @Action(input = "http://controllers.cmi.api.ensas.com/CmiWebService/getListCreancierRequest", output = "http://controllers.cmi.api.ensas.com/CmiWebService/getListCreancierResponse")
    public List<Creancier> getListCreancier();

    /**
     * 
     * @param codeCreancier
     * @param codeCreance
     * @return
     *     returns mypackage.ResultImpaye
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImpayes", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetImpayes")
    @ResponseWrapper(localName = "getImpayesResponse", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetImpayesResponse")
    @Action(input = "http://controllers.cmi.api.ensas.com/CmiWebService/getImpayesRequest", output = "http://controllers.cmi.api.ensas.com/CmiWebService/getImpayesResponse")
    public ResultImpaye getImpayes(
        @WebParam(name = "codeCreancier", targetNamespace = "")
        String codeCreancier,
        @WebParam(name = "codeCreance", targetNamespace = "")
        String codeCreance);

    /**
     * 
     * @param codeCreancier
     * @param codeImpaye
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmePaye", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.ConfirmePaye")
    @ResponseWrapper(localName = "confirmePayeResponse", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.ConfirmePayeResponse")
    @Action(input = "http://controllers.cmi.api.ensas.com/CmiWebService/confirmePayeRequest", output = "http://controllers.cmi.api.ensas.com/CmiWebService/confirmePayeResponse")
    public boolean confirmePaye(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "codeCreancier", targetNamespace = "")
        String codeCreancier,
        @WebParam(name = "codeImpaye", targetNamespace = "")
        String codeImpaye);

    /**
     * 
     * @param password
     * @param token
     */
    @WebMethod
    @RequestWrapper(localName = "setClientPassword", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.SetClientPassword")
    @ResponseWrapper(localName = "setClientPasswordResponse", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.SetClientPasswordResponse")
    @Action(input = "http://controllers.cmi.api.ensas.com/CmiWebService/setClientPasswordRequest", output = "http://controllers.cmi.api.ensas.com/CmiWebService/setClientPasswordResponse")
    public void setClientPassword(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSolde", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetSolde")
    @ResponseWrapper(localName = "getSoldeResponse", targetNamespace = "http://controllers.cmi.api.ensas.com/", className = "mypackage.GetSoldeResponse")
    @Action(input = "http://controllers.cmi.api.ensas.com/CmiWebService/getSoldeRequest", output = "http://controllers.cmi.api.ensas.com/CmiWebService/getSoldeResponse")
    public Double getSolde(
        @WebParam(name = "token", targetNamespace = "")
        String token);

}
